name: app_environment
channels:
  - snowflake
dependencies:
  - python=3.8.*
  - snowflake=0.12.0
  - snowflake-ml-python=1.6.1
  - snowflake-snowpark-python=
  - snowflake-connector-python=
  - streamlit=


