name: app_environment
channels:
  - conda-forge
  - defaults  # Necessary for core packages
dependencies:
  - python=3.8.*  # Specify the Python version
  - snowflake=0.12.1
  - streamlit  # Specify version if needed
  - snowflake-connector-python
  - snowflake-snowpark-python
  - snowflake-ml-python  # Optional, include if you need ML capabilities
  - pip  # Ensure pip is installed
  - pip:
      - snowflake-cortex  # Required for snowflake.cortex
      - transformers  # Optional, if you plan to use Hugging Face models
