name: app_environment
channels:
  - conda-forge
  - defaults  # Defaults is necessary to resolve core packages like Python
dependencies:
  - python=3.8.*  # Specify the Python version
  - streamlit  # Add version if needed, e.g., streamlit=0.87.0
  - snowflake-connector-python
  - snowflake-snowpark-python
  - snowflake-ml-python
  - pip  # Ensure pip is installed
  - pip:
      - snowflake
      - snowflake-connector-python  # Install using pip
      - snowflake-snowpark-python
      - snowflake-ml-python
      


