  name: app_environment
channels:
  - conda-forge  # Use conda-forge for broader package availability
  - snowflake
dependencies:
  - python=3.8.*  # Specify the Python version
  - streamlit  # Specify the version if needed, e.g., streamlit=0.87.0
  - snowflake-connector-python  # Use pip for these packages
  - snowflake-snowpark-python
  - snowflake-ml-python
  - pip  # Ensure pip is installed
  - pip:
      - snowflake-connector-python  # Install using pip
      - snowflake-snowpark-python
      - snowflake-ml-python


