name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8

      - name: Initialize Conda and create environment
        shell: bash
        run: |
          # Initialize Conda in the shell
          conda init bash
          source ~/.bashrc  # Reload bash configuration to apply changes
          
          # Create and activate the environment
          conda env create -f environment.yml
          source ~/.bashrc  # Make sure environment settings are applied again
          conda activate app_environment

      - name: Verify Python version and dependencies
        run: |
          python --version
          pip freeze

      - name: Run Streamlit app
        run: |
          source ~/.bashrc  # Ensure the environment is active
          conda activate app_environment
          streamlit run streamlit_app.py --server.port=8501
