name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8

      - name: Initialize Conda
        shell: bash
        run: |
          conda init bash  # Initialize Conda in bash shell
          source ~/.bashrc # Reload bash configuration

      - name: Create conda environment from environment.yml
        shell: bash
        run: |
          conda env create -f environment.yml
          source ~/.bashrc
          conda activate app_environment

      - name: Verify Python version and dependencies
        run: |
          python --version
          pip freeze

      - name: Run Streamlit app
        run: |
          conda activate app_environment
          streamlit run streamlit_app.py --server.port=8501
